name: Default

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        uses: docker://thulioassis/bazel-docker-image:2.0.0
        with:
          entrypoint: bazel
          args: run //:buildifier
      - name: Test
        uses: docker://thulioassis/bazel-docker-image:2.0.0
        with:
          entrypoint: bazel
          args: test //...
